name: atta
description: Atta project is restaurant app reservation.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  cloud_firestore: ^4.14.0
  collection: ^1.17.2
  crypto: ^3.0.3
  cupertino_icons: ^1.0.6
  faker: ^2.1.0
  firebase_auth: ^4.16.0
  firebase_core: ^2.24.2
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_localizations:
    sdk: flutter  
  go_router: ^13.0.1
  google_sign_in: ^6.2.1
  intl: ^0.18.1
  rxdart: ^0.27.7
  sliver_tools: ^0.2.12
  url_launcher: ^6.2.1

dev_dependencies:
  build_runner: ^2.4.8
  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/logo/
    - assets/icons/

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-VariableFont.ttf
    - family: WorkSans
      fonts:
        - asset: assets/fonts/WorkSans-VariableFont.ttf