name: atta
description: Atta project is restaurant app reservation.

publish_to: 'none' 

version: 0.2.1+13

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  cached_network_image: ^3.3.1
  collection: ^1.17.2
  crypto: ^3.0.3
  cupertino_icons: ^1.0.6
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_isolate: ^2.0.5-pre
  flutter_localizations:
    sdk: flutter  
  flutter_map: ^6.1.0
  flutter_map_animations: ^0.5.3
  flutter_map_marker_cluster: ^1.3.4
  go_router: ^13.0.1
  google_sign_in: ^6.2.1
  image_picker: ^1.0.7
  intl: ^0.18.1
  latlong2: ^0.9.0
  maps_launcher: ^2.2.0
  rxdart: ^0.27.7
  share_plus: ^7.2.2
  sliver_tools: ^0.2.12
  supabase_flutter: ^2.3.1
  url_launcher: ^6.2.1

dev_dependencies:
  build_runner: ^2.4.8
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/logo/text_colored.png"
  min_sdk_android: 21
  adaptive_icon_background: "#FFFFFF"
  web:
    generate: true
    image_path: "assets/logo/text_colored.png"
    background_color: "#FFFFFF"
    theme_color: "#FFFFFF"

flutter:
  uses-material-design: true

  assets:
    - assets/logo/
    - assets/icons/

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-VariableFont.ttf
    - family: WorkSans
      fonts:
        - asset: assets/fonts/WorkSans-VariableFont.ttf