// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDEZD3jOpAFRjVAIkAu7cl4W2N-iHp3o3w',
    appId: '1:265601211863:web:89f33cef157c211b65ff92',
    messagingSenderId: '265601211863',
    projectId: 'atta-979bf',
    authDomain: 'atta-979bf.firebaseapp.com',
    storageBucket: 'atta-979bf.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCKCzuAMtU7ScOhQuArXX9AMgTzulJ05kM',
    appId: '1:265601211863:android:e4e2245068b5df8a65ff92',
    messagingSenderId: '265601211863',
    projectId: 'atta-979bf',
    storageBucket: 'atta-979bf.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA7IZZGLdnJQ9Zkg_woN_xndnxd66K7kRs',
    appId: '1:265601211863:ios:22a3e39b2dc7876b65ff92',
    messagingSenderId: '265601211863',
    projectId: 'atta-979bf',
    storageBucket: 'atta-979bf.appspot.com',
    iosClientId: '265601211863-v0ia8vojnvugjruf56rp6d2h75n1tv0s.apps.googleusercontent.com',
    iosBundleId: 'com.example.atta',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA7IZZGLdnJQ9Zkg_woN_xndnxd66K7kRs',
    appId: '1:265601211863:ios:713aba4f49e0589e65ff92',
    messagingSenderId: '265601211863',
    projectId: 'atta-979bf',
    storageBucket: 'atta-979bf.appspot.com',
    iosClientId: '265601211863-pfa12aajq2fpr5holf1h96fbq2m7pueq.apps.googleusercontent.com',
    iosBundleId: 'com.example.atta.RunnerTests',
  );
}
