name: Call Reusable Workflow

on:
  push:
    branches:
      - main

jobs:
  call-workflow:
    uses: sepios87/Workflow-flutter/.github/workflows/flutter_workflow.yml@main
    with:
      flutter_version: '3.19.6'
      min_percent_comment: 0
      build_apk: true
